# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sourcify}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["NgTzeYang"]
  s.date = %q{2010-08-28}
  s.description = %q{}
  s.email = %q{ngty77@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "HISTORY.txt",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/sourcify.rb",
     "lib/sourcify/proc.rb",
     "lib/sourcify/proc/counter.rb",
     "lib/sourcify/proc/lexer.rb",
     "lib/sourcify/proc/lexer18.rb",
     "lib/sourcify/proc/lexer19.rb",
     "lib/sourcify/proc/parser.rb",
     "sourcify.gemspec",
     "spec/proc/19x_extras.rb",
     "spec/proc/readme",
     "spec/proc/to_sexp_variables_spec.rb",
     "spec/proc/to_source_from_braced_block_w_nested_braced_block_spec.rb",
     "spec/proc/to_source_from_braced_block_w_nested_hash_spec.rb",
     "spec/proc/to_source_from_braced_block_wo_nesting_complication_spec.rb",
     "spec/proc/to_source_from_do_end_block_w_nested_begin_spec.rb",
     "spec/proc/to_source_from_do_end_block_w_nested_case_spec.rb",
     "spec/proc/to_source_from_do_end_block_w_nested_class_spec.rb",
     "spec/proc/to_source_from_do_end_block_w_nested_do_end_block_spec.rb",
     "spec/proc/to_source_from_do_end_block_w_nested_for_spec.rb",
     "spec/proc/to_source_from_do_end_block_w_nested_if_spec.rb",
     "spec/proc/to_source_from_do_end_block_w_nested_method_spec.rb",
     "spec/proc/to_source_from_do_end_block_w_nested_module_spec.rb",
     "spec/proc/to_source_from_do_end_block_w_nested_unless_spec.rb",
     "spec/proc/to_source_from_do_end_block_w_nested_until_spec.rb",
     "spec/proc/to_source_from_do_end_block_w_nested_while_spec.rb",
     "spec/proc/to_source_from_do_end_block_wo_nesting_complication_spec.rb",
     "spec/proc/to_source_from_multi_blocks_w_many_matches_spec.rb",
     "spec/proc/to_source_from_multi_blocks_w_single_match_spec.rb",
     "spec/proc/to_source_from_multi_do_end_blocks_w_single_match_spec.rb",
     "spec/proc/to_source_magic_file_var_spec.rb",
     "spec/proc/to_source_magic_line_var_spec.rb",
     "spec/proc/to_source_variables_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/ngty/sourcify}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Workarounds before ruby-core officially supports Proc#to_source (& friends)}
  s.test_files = [
    "spec/proc/to_source_from_do_end_block_w_nested_until_spec.rb",
     "spec/proc/to_source_from_do_end_block_w_nested_begin_spec.rb",
     "spec/proc/to_source_from_braced_block_w_nested_hash_spec.rb",
     "spec/proc/to_source_from_braced_block_wo_nesting_complication_spec.rb",
     "spec/proc/to_source_from_do_end_block_w_nested_while_spec.rb",
     "spec/proc/to_source_from_multi_do_end_blocks_w_single_match_spec.rb",
     "spec/proc/to_source_from_multi_blocks_w_many_matches_spec.rb",
     "spec/proc/to_source_from_multi_blocks_w_single_match_spec.rb",
     "spec/proc/to_source_from_do_end_block_w_nested_module_spec.rb",
     "spec/proc/to_source_from_do_end_block_w_nested_do_end_block_spec.rb",
     "spec/proc/to_source_from_do_end_block_w_nested_method_spec.rb",
     "spec/proc/to_source_from_do_end_block_w_nested_class_spec.rb",
     "spec/proc/to_source_from_do_end_block_w_nested_case_spec.rb",
     "spec/proc/to_source_magic_line_var_spec.rb",
     "spec/proc/to_source_from_do_end_block_w_nested_unless_spec.rb",
     "spec/proc/19x_extras.rb",
     "spec/proc/to_source_from_braced_block_w_nested_braced_block_spec.rb",
     "spec/proc/to_source_from_do_end_block_wo_nesting_complication_spec.rb",
     "spec/proc/to_source_variables_spec.rb",
     "spec/proc/to_sexp_variables_spec.rb",
     "spec/proc/to_source_magic_file_var_spec.rb",
     "spec/proc/to_source_from_do_end_block_w_nested_if_spec.rb",
     "spec/proc/to_source_from_do_end_block_w_nested_for_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruby2ruby>, [">= 1.2.4"])
      s.add_development_dependency(%q<bacon>, [">= 0"])
    else
      s.add_dependency(%q<ruby2ruby>, [">= 1.2.4"])
      s.add_dependency(%q<bacon>, [">= 0"])
    end
  else
    s.add_dependency(%q<ruby2ruby>, [">= 1.2.4"])
    s.add_dependency(%q<bacon>, [">= 0"])
  end
end

